backend/models/Products.php
<?php

namespace app\models;

use Yii;
use yii\bootstrap\Alert;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property string|null $name
 * @property int|null $category_id
 * @property string|null $price
 * @property string|null $description
 *
 * @property Categories $category
 */
class Products extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id'], 'integer'],
            [['description'], 'string'],
            [['name', 'price'], 'string', 'max' => 255],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Categories::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'category_id' => 'Category ID',
            'price' => 'Price',
            'description' => 'Description',
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Categories::className(), ['id' => 'category_id']);
    }

}

frontend/models/Product.php
<?php

namespace app\models;

use Yii;
use yii\data\Pagination;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property string|null $name
 * @property int|null $category_id
 * @property string|null $price
 * @property string|null $description
 *
 * @property Categories $category
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id'], 'integer'],
            [['description'], 'string'],
            [['name', 'price'], 'string', 'max' => 255],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Categories::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'category_id' => 'Category ID',
            'price' => 'Price',
            'description' => 'Description',
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Categories::className(), ['id' => 'category_id']);
    }

    public static function getProductByCategory($id)
    {
        if ($id == null) {
            $query = Product::find();
        } else $query = Product::find()->where(['category_id' => $id]);

        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize'=>6]);
        $products = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        $data['products'] = $products;
        $data['pages'] = $pages;

        return $data;
    }
}

backend/controllers/ProductsController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Products;
use app\models\Images;
use app\models\ProductsSearch;
use common\models\LoginForm;
use backend\models\UploadForm;
use yii\web\UploadedFile;


/**
 * ProductsController implements the CRUD actions for Products model.
 */
class ProductsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Products models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Products model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Products model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Products();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Products model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Products model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Products model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Products the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Products::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionUpload($id)
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost)
        {
            $product = $this->findModel($id);
            $model->imageFiles = UploadedFile::getInstances($model, 'imageFiles');
            foreach ($model->upload($arr) as $item) {
                $image = new Images();
                $image->saveImage($id, $item);
            } return $this->redirect(['view', 'id'=>$product->id]);
        }
        return $this->render('upload', ['model' => $model]);
    }

}

frontend/controllers/ProductController.php
<?php

namespace frontend\controllers;

use yii\web\Controller;
use app\models\Product;
use app\models\Images;
use app\models\Categories;
//use yii\data\Pagination;

class ProductController extends \yii\web\Controller
{
    public function actionIndex($id)
    {
        if ($id == NULL) {
            $data = Product::getProductByCategory(NULL);
        } else $data = Product::getProductByCategory($id);
	    $categories = Categories::getAll();

	    return $this->render('index', [
	         'products' => $data['products'],
	         'pages' => $data['pages'],
	         'categories' => $categories,
	    ]);
    }

    public function actionView($id)
    {
        $product = Product::findOne($id);

        return $this->render('view', ['product'=>$product]);
    }

}

frontend/views/product/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;
use app\models\Product;
use app\models\Images;
use app\models\Categories;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Товары';
$this->params['breadcrumbs'][] = $this->title;
?>

<!--main content start-->
<div class="main">
    <div class="container">
        <div class="row">
            <?= $this->render('/partials/sidebar', [
                'categories' => $categories,
            ]); ?>
            <div class="col-md-9">
                <?php foreach ($products as $product): ?>
                    <div class="col-md-6">
                        <h3><a href="<?= Url::toRoute(['product/view', 'id'=>$product->id]);?>"><?= $product->name?></a></h3>
                        <h4>Цена: <?= $product->price?> руб.</h4>
                        <a href="<?= Url::toRoute(['product/view', 'id'=>$product->id]);?>"><?= Html::img('@web/uploads/' . Images::getFirstImageByProduct($product->id, 0), ['alt' => 'Изображение товара', 'width' => '350']);?></a>
                        <br/>
                        <br/>
                    </div>
                <?php endforeach; ?>
            </div> 
            <?php
                echo LinkPager::widget([
                    'pagination' => $pages,
                ]);
            ?> 
        </div>
    </div>
</div>
<!-- end main content-->

frontend/views/product/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\Images;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Товар';
$this->params['breadcrumbs'][] = $this->title;

?>

<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- fotorama.css & fotorama.js. -->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
</head>

<!--main content start-->
<div class="main">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="row">
                    <div class="fotorama">
                        <?= Html::img('@web/uploads/' . Images::getFirstImageByProduct($product->id, 0), ['alt' => 'Изображение товара']) ?>
                        <?= Html::img('@web/uploads/' . Images::getFirstImageByProduct($product->id, 1), ['alt' => 'Изображение товара']) ?>
                        <?= Html::img('@web/uploads/' . Images::getFirstImageByProduct($product->id, 2), ['alt' => 'Изображение товара']) ?>
                        <?= Html::img('@web/uploads/' . Images::getFirstImageByProduct($product->id, 3), ['alt' => 'Изображение товара']) ?>
                        <?= Html::img('@web/uploads/' . Images::getFirstImageByProduct($product->id, 4), ['alt' => 'Изображение товара']) ?>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    <h2>Наименование: <strong><?= $product->name?></strong></h2>
                </div>
                <div>
                    <h3>Цена: <?= $product->price?> руб.</h3>
                </div>
                <br>
                <div>
                    <h4>Описание:</h4>
                    <p><?= $product->description?></p>
                </div>
            </div>  
        </div>
    </div>
</div>
<!-- end main content-->